blank_issues_enabled: false
contact_links:
  - name: Feature Request
    url: https://github.com/WirlyWirly/quiCKIE/discussions/new?category=feature-request
    about: Start a Discussion For a New Feature Request

